// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: ridepath.proto

package panynj

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Contains information about all incoming trains at all stations
type RidePathResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// All station data.
	Results []*RidePathResponse_Results `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *RidePathResponse) Reset() {
	*x = RidePathResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ridepath_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RidePathResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RidePathResponse) ProtoMessage() {}

func (x *RidePathResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ridepath_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RidePathResponse.ProtoReflect.Descriptor instead.
func (*RidePathResponse) Descriptor() ([]byte, []int) {
	return file_ridepath_proto_rawDescGZIP(), []int{0}
}

func (x *RidePathResponse) GetResults() []*RidePathResponse_Results {
	if x != nil {
		return x.Results
	}
	return nil
}

// Information about a single train
type RidePathResponse_Messages struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The target station
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	// The estimated number of seconds until the train arrives
	SecondsToArrival string `protobuf:"bytes,2,opt,name=secondsToArrival,proto3" json:"secondsToArrival,omitempty"`
	// A formatted message to display to the user
	ArrivalTimeMessage string `protobuf:"bytes,3,opt,name=arrivalTimeMessage,proto3" json:"arrivalTimeMessage,omitempty"`
	// The color associated with the route. Can be multiple colors
	// delimited by commas (e.g. the for JSQ-33-HOB).
	LineColor string `protobuf:"bytes,4,opt,name=lineColor,proto3" json:"lineColor,omitempty"`
	// The headsign for the trip
	HeadSign string `protobuf:"bytes,5,opt,name=headSign,proto3" json:"headSign,omitempty"`
	// An ISO 8601 formatted string for when this data was last updated.
	LastUpdated string `protobuf:"bytes,6,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
}

func (x *RidePathResponse_Messages) Reset() {
	*x = RidePathResponse_Messages{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ridepath_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RidePathResponse_Messages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RidePathResponse_Messages) ProtoMessage() {}

func (x *RidePathResponse_Messages) ProtoReflect() protoreflect.Message {
	mi := &file_ridepath_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RidePathResponse_Messages.ProtoReflect.Descriptor instead.
func (*RidePathResponse_Messages) Descriptor() ([]byte, []int) {
	return file_ridepath_proto_rawDescGZIP(), []int{0, 0}
}

func (x *RidePathResponse_Messages) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RidePathResponse_Messages) GetSecondsToArrival() string {
	if x != nil {
		return x.SecondsToArrival
	}
	return ""
}

func (x *RidePathResponse_Messages) GetArrivalTimeMessage() string {
	if x != nil {
		return x.ArrivalTimeMessage
	}
	return ""
}

func (x *RidePathResponse_Messages) GetLineColor() string {
	if x != nil {
		return x.LineColor
	}
	return ""
}

func (x *RidePathResponse_Messages) GetHeadSign() string {
	if x != nil {
		return x.HeadSign
	}
	return ""
}

func (x *RidePathResponse_Messages) GetLastUpdated() string {
	if x != nil {
		return x.LastUpdated
	}
	return ""
}

// A labeled direction  with associated trains.
type RidePathResponse_Destinations struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The direction of the trains (either 'ToNJ' to 'ToNY')
	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	// All trains headed to the above direction.
	Messages []*RidePathResponse_Messages `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
}

func (x *RidePathResponse_Destinations) Reset() {
	*x = RidePathResponse_Destinations{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ridepath_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RidePathResponse_Destinations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RidePathResponse_Destinations) ProtoMessage() {}

func (x *RidePathResponse_Destinations) ProtoReflect() protoreflect.Message {
	mi := &file_ridepath_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RidePathResponse_Destinations.ProtoReflect.Descriptor instead.
func (*RidePathResponse_Destinations) Descriptor() ([]byte, []int) {
	return file_ridepath_proto_rawDescGZIP(), []int{0, 1}
}

func (x *RidePathResponse_Destinations) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *RidePathResponse_Destinations) GetMessages() []*RidePathResponse_Messages {
	if x != nil {
		return x.Messages
	}
	return nil
}

// All destinations for a given station.
type RidePathResponse_Results struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The station.
	ConsideredStation string `protobuf:"bytes,1,opt,name=consideredStation,proto3" json:"consideredStation,omitempty"`
	// Destinations associated with the station.
	Destinations []*RidePathResponse_Destinations `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
}

func (x *RidePathResponse_Results) Reset() {
	*x = RidePathResponse_Results{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ridepath_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RidePathResponse_Results) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RidePathResponse_Results) ProtoMessage() {}

func (x *RidePathResponse_Results) ProtoReflect() protoreflect.Message {
	mi := &file_ridepath_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RidePathResponse_Results.ProtoReflect.Descriptor instead.
func (*RidePathResponse_Results) Descriptor() ([]byte, []int) {
	return file_ridepath_proto_rawDescGZIP(), []int{0, 2}
}

func (x *RidePathResponse_Results) GetConsideredStation() string {
	if x != nil {
		return x.ConsideredStation
	}
	return ""
}

func (x *RidePathResponse_Results) GetDestinations() []*RidePathResponse_Destinations {
	if x != nil {
		return x.Destinations
	}
	return nil
}

var File_ridepath_proto protoreflect.FileDescriptor

var file_ridepath_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x69, 0x64, 0x65, 0x70, 0x61, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0xff, 0x03, 0x0a, 0x10, 0x52, 0x69, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x50, 0x61, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xda, 0x01, 0x0a, 0x08, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12,
	0x2a, 0x0a, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x54, 0x6f, 0x41, 0x72, 0x72, 0x69,
	0x76, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x73, 0x65, 0x63, 0x6f, 0x6e,
	0x64, 0x73, 0x54, 0x6f, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x12, 0x2e, 0x0a, 0x12, 0x61,
	0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x61, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x65, 0x61,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x65, 0x61,
	0x64, 0x53, 0x69, 0x67, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x1a, 0x5c, 0x0a, 0x0c, 0x44, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x36, 0x0a,
	0x08, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x1a, 0x7b, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x64, 0x65, 0x72, 0x65, 0x64, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6f, 0x6e,
	0x73, 0x69, 0x64, 0x65, 0x72, 0x65, 0x64, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x42,
	0x0a, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x52, 0x69, 0x64, 0x65, 0x50, 0x61, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0c, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x51, 0x42, 0x0d, 0x52, 0x69, 0x64, 0x65, 0x70, 0x61, 0x74, 0x68, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x3e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6a, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x66, 0x65, 0x6e, 0x6e, 0x65, 0x6c, 0x6c, 0x2f,
	0x70, 0x61, 0x74, 0x68, 0x2d, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x2d, 0x67, 0x74, 0x66, 0x73, 0x2d,
	0x72, 0x65, 0x61, 0x6c, 0x74, 0x69, 0x6d, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x61, 0x6e, 0x79, 0x6e, 0x6a, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ridepath_proto_rawDescOnce sync.Once
	file_ridepath_proto_rawDescData = file_ridepath_proto_rawDesc
)

func file_ridepath_proto_rawDescGZIP() []byte {
	file_ridepath_proto_rawDescOnce.Do(func() {
		file_ridepath_proto_rawDescData = protoimpl.X.CompressGZIP(file_ridepath_proto_rawDescData)
	})
	return file_ridepath_proto_rawDescData
}

var file_ridepath_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_ridepath_proto_goTypes = []interface{}{
	(*RidePathResponse)(nil),              // 0: RidePathResponse
	(*RidePathResponse_Messages)(nil),     // 1: RidePathResponse.Messages
	(*RidePathResponse_Destinations)(nil), // 2: RidePathResponse.Destinations
	(*RidePathResponse_Results)(nil),      // 3: RidePathResponse.Results
}
var file_ridepath_proto_depIdxs = []int32{
	3, // 0: RidePathResponse.results:type_name -> RidePathResponse.Results
	1, // 1: RidePathResponse.Destinations.messages:type_name -> RidePathResponse.Messages
	2, // 2: RidePathResponse.Results.destinations:type_name -> RidePathResponse.Destinations
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ridepath_proto_init() }
func file_ridepath_proto_init() {
	if File_ridepath_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ridepath_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RidePathResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ridepath_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RidePathResponse_Messages); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ridepath_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RidePathResponse_Destinations); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ridepath_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RidePathResponse_Results); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ridepath_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ridepath_proto_goTypes,
		DependencyIndexes: file_ridepath_proto_depIdxs,
		MessageInfos:      file_ridepath_proto_msgTypes,
	}.Build()
	File_ridepath_proto = out.File
	file_ridepath_proto_rawDesc = nil
	file_ridepath_proto_goTypes = nil
	file_ridepath_proto_depIdxs = nil
}
