// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0-devel
// 	protoc        v3.6.0
// source: common.proto

package path_api_v1

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Full list of all PATH stations in the system.
type Station int32

const (
	Station_STATION_UNSPECIFIED Station = 0
	Station_NEWARK              Station = 1
	Station_HARRISON            Station = 2
	Station_JOURNAL_SQUARE      Station = 3
	Station_GROVE_STREET        Station = 4
	Station_EXCHANGE_PLACE      Station = 5
	Station_WORLD_TRADE_CENTER  Station = 6
	Station_NEWPORT             Station = 7
	Station_HOBOKEN             Station = 8
	Station_CHRISTOPHER_STREET  Station = 9
	Station_NINTH_STREET        Station = 10
	Station_FOURTEENTH_STREET   Station = 11
	Station_TWENTY_THIRD_STREET Station = 12
	Station_THIRTY_THIRD_STREET Station = 13
)

// Enum value maps for Station.
var (
	Station_name = map[int32]string{
		0:  "STATION_UNSPECIFIED",
		1:  "NEWARK",
		2:  "HARRISON",
		3:  "JOURNAL_SQUARE",
		4:  "GROVE_STREET",
		5:  "EXCHANGE_PLACE",
		6:  "WORLD_TRADE_CENTER",
		7:  "NEWPORT",
		8:  "HOBOKEN",
		9:  "CHRISTOPHER_STREET",
		10: "NINTH_STREET",
		11: "FOURTEENTH_STREET",
		12: "TWENTY_THIRD_STREET",
		13: "THIRTY_THIRD_STREET",
	}
	Station_value = map[string]int32{
		"STATION_UNSPECIFIED": 0,
		"NEWARK":              1,
		"HARRISON":            2,
		"JOURNAL_SQUARE":      3,
		"GROVE_STREET":        4,
		"EXCHANGE_PLACE":      5,
		"WORLD_TRADE_CENTER":  6,
		"NEWPORT":             7,
		"HOBOKEN":             8,
		"CHRISTOPHER_STREET":  9,
		"NINTH_STREET":        10,
		"FOURTEENTH_STREET":   11,
		"TWENTY_THIRD_STREET": 12,
		"THIRTY_THIRD_STREET": 13,
	}
)

func (x Station) Enum() *Station {
	p := new(Station)
	*p = x
	return p
}

func (x Station) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Station) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (Station) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x Station) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Station.Descriptor instead.
func (Station) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

// Full list of all routes within the system.
type Route int32

const (
	Route_ROUTE_UNSPECIFIED Route = 0
	// Journal Square to 33rd Street via Hoboken
	Route_JSQ_33_HOB Route = 1
	// Hoboken to 33rd Street
	Route_HOB_33 Route = 2
	// Hoboken to World Trade Center
	Route_HOB_WTC Route = 3
	// Journal Square to 33rd Street
	Route_JSQ_33 Route = 4
	// Newark to World Trade Center
	Route_NWK_WTC Route = 5
)

// Enum value maps for Route.
var (
	Route_name = map[int32]string{
		0: "ROUTE_UNSPECIFIED",
		1: "JSQ_33_HOB",
		2: "HOB_33",
		3: "HOB_WTC",
		4: "JSQ_33",
		5: "NWK_WTC",
	}
	Route_value = map[string]int32{
		"ROUTE_UNSPECIFIED": 0,
		"JSQ_33_HOB":        1,
		"HOB_33":            2,
		"HOB_WTC":           3,
		"JSQ_33":            4,
		"NWK_WTC":           5,
	}
)

func (x Route) Enum() *Route {
	p := new(Route)
	*p = x
	return p
}

func (x Route) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Route) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[1].Descriptor()
}

func (Route) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[1]
}

func (x Route) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Route.Descriptor instead.
func (Route) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

// Directions trains can travel along routes.
type Direction int32

const (
	Direction_DIRECTION_UNSPECIFIED Direction = 0
	Direction_TO_NJ                 Direction = 1
	Direction_TO_NY                 Direction = 2
)

// Enum value maps for Direction.
var (
	Direction_name = map[int32]string{
		0: "DIRECTION_UNSPECIFIED",
		1: "TO_NJ",
		2: "TO_NY",
	}
	Direction_value = map[string]int32{
		"DIRECTION_UNSPECIFIED": 0,
		"TO_NJ":                 1,
		"TO_NY":                 2,
	}
)

func (x Direction) Enum() *Direction {
	p := new(Direction)
	*p = x
	return p
}

func (x Direction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Direction) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[2].Descriptor()
}

func (Direction) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[2]
}

func (x Direction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Direction.Descriptor instead.
func (Direction) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{2}
}

var File_common_proto protoreflect.FileDescriptor

var file_common_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b,
	0x70, 0x61, 0x74, 0x68, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2a, 0x9b, 0x02, 0x0a, 0x07,
	0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x17, 0x0a, 0x13, 0x53, 0x54, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x45, 0x57, 0x41, 0x52, 0x4b, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x48, 0x41, 0x52, 0x52, 0x49, 0x53, 0x4f, 0x4e, 0x10, 0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4a, 0x4f,
	0x55, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x53, 0x51, 0x55, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12, 0x10,
	0x0a, 0x0c, 0x47, 0x52, 0x4f, 0x56, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x04,
	0x12, 0x12, 0x0a, 0x0e, 0x45, 0x58, 0x43, 0x48, 0x41, 0x4e, 0x47, 0x45, 0x5f, 0x50, 0x4c, 0x41,
	0x43, 0x45, 0x10, 0x05, 0x12, 0x16, 0x0a, 0x12, 0x57, 0x4f, 0x52, 0x4c, 0x44, 0x5f, 0x54, 0x52,
	0x41, 0x44, 0x45, 0x5f, 0x43, 0x45, 0x4e, 0x54, 0x45, 0x52, 0x10, 0x06, 0x12, 0x0b, 0x0a, 0x07,
	0x4e, 0x45, 0x57, 0x50, 0x4f, 0x52, 0x54, 0x10, 0x07, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x4f, 0x42,
	0x4f, 0x4b, 0x45, 0x4e, 0x10, 0x08, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x48, 0x52, 0x49, 0x53, 0x54,
	0x4f, 0x50, 0x48, 0x45, 0x52, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x09, 0x12, 0x10,
	0x0a, 0x0c, 0x4e, 0x49, 0x4e, 0x54, 0x48, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x0a,
	0x12, 0x15, 0x0a, 0x11, 0x46, 0x4f, 0x55, 0x52, 0x54, 0x45, 0x45, 0x4e, 0x54, 0x48, 0x5f, 0x53,
	0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x0b, 0x12, 0x17, 0x0a, 0x13, 0x54, 0x57, 0x45, 0x4e, 0x54,
	0x59, 0x5f, 0x54, 0x48, 0x49, 0x52, 0x44, 0x5f, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x0c,
	0x12, 0x17, 0x0a, 0x13, 0x54, 0x48, 0x49, 0x52, 0x54, 0x59, 0x5f, 0x54, 0x48, 0x49, 0x52, 0x44,
	0x5f, 0x53, 0x54, 0x52, 0x45, 0x45, 0x54, 0x10, 0x0d, 0x2a, 0x60, 0x0a, 0x05, 0x52, 0x6f, 0x75,
	0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x52, 0x4f, 0x55, 0x54, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x4a, 0x53, 0x51,
	0x5f, 0x33, 0x33, 0x5f, 0x48, 0x4f, 0x42, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x4f, 0x42,
	0x5f, 0x33, 0x33, 0x10, 0x02, 0x12, 0x0b, 0x0a, 0x07, 0x48, 0x4f, 0x42, 0x5f, 0x57, 0x54, 0x43,
	0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x4a, 0x53, 0x51, 0x5f, 0x33, 0x33, 0x10, 0x04, 0x12, 0x0b,
	0x0a, 0x07, 0x4e, 0x57, 0x4b, 0x5f, 0x57, 0x54, 0x43, 0x10, 0x05, 0x2a, 0x3c, 0x0a, 0x09, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x15, 0x44, 0x49, 0x52, 0x45,
	0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x54, 0x4f, 0x5f, 0x4e, 0x4a, 0x10, 0x01, 0x12, 0x09,
	0x0a, 0x05, 0x54, 0x4f, 0x5f, 0x4e, 0x59, 0x10, 0x02, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData = file_common_proto_rawDesc
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_proto_rawDescData)
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_common_proto_goTypes = []interface{}{
	(Station)(0),   // 0: path_api.v1.Station
	(Route)(0),     // 1: path_api.v1.Route
	(Direction)(0), // 2: path_api.v1.Direction
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_rawDesc = nil
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
